### ISSUE TITLE
Transfer Learning or Training model on personal dataset

### ISSUE THREAD

**Issue by pranavgundewar** [lld533/Grid-Anchor-based-Image-Cropping-Pytorch#4]
Hi!

Thanks for the great work and for sharing the codebase. I have a small dataset consists of approx 200 images and wanted to carry out training/transfer learning of the mobile-net based model.
However, for my images, the good crops are not obtained for the given aspect ratio.
I wanted to ask if you can explain ways to modify annotation software as well as ways to train the model on new data or if I can leverage transfer learning. Thank you!

**Comment by lld533** [comment]
> Hi!
> 
> Thanks for the great work and for sharing the codebase. I have a small dataset consists of approx 200 images and wanted to carry out training/transfer learning of the mobile-net based model.
> However, for my images, the good crops are not obtained for the given aspect ratio.
> I wanted to ask if you can explain ways to modify annotation software as well as ways to train the model on new data or if I can leverage transfer learning. Thank you!

If you are familiar with WPF development, 
1/ have a look at  annotation/ref_code/MainWindowViewModel.cs; 
2/ introduce your own aspect ratio;
3/ double check the existing grids as well as upper/lower aspect ratio; if they do not match the new aspect ratio, update them;
4/ build your own project in Visual Studio or Blend and include the .cs file;
5/ in sake of MV-VM design pattern, view is left so you need to build up your own UI in your .xaml file;
6/ compile and check your project and have fun.

If you are not familiar with WPF, try to develop your own annotation software with other toolkits, e.g. PyQT, iOS/Android App, etc.

Due to social activities in HK in the past few months, we have NO access to our own source codes at the time being. Sorry for any inconvenience.
